language: it # it or en

environment: dev

telegram:
    token: 'telegram_bot_token_here'

permissions:
    events:
        create: [ 'anyone' ] # anyone or a list of username
        modify: 'owner'      # owner or anyone
        publish: 'owner'     # owner or anyone
        reminder: 'owner'    # owner or anyone